### PR TITLE
changed to match the service start script

### PR DESCRIPTION
**Pull request by uharband**

### CODE REVIEW

**Comment by erivni** [comment]
👍

**Comment by zoonage** [comment]
SystemD method uses `ExecStart=/usr/bin/{{name}} ${{name|upper}}_OPTS` https://github.com/lest/prometheus-rpm/blob/master/templates/unit.tpl#L14. So I think this would break on CentOS 7, would need to be tested though

**Comment by lest** [comment]
> It would probably be easier to change `EXPORTER_ARGS` to `${NAME}_ARGS` in the init script. This will probably have a conflict with #83 though

I agree that it's better to update the init script to use `${NAME}_ARGS`. CentOS 6 support has been added only recently, so majority of people have packages installed under CentOS 7 and we don't want to break their configuration.

**Comment by karlism** [comment]
Closing as we've just dropped CentOS 6 support.

**Pull request closed without merging**
