### PR TITLE
Update Prometheus to 2.24.0

### PR DESCRIPTION
**Pull request by karlism**
[FEATURE] Add TLS and basic authentication to HTTP endpoints. #8316
[FEATURE] promtool: Add check web-config subcommand to check web config files. #8319
[FEATURE] promtool: Add tsdb create-blocks-from openmetrics subcommand to backfill metrics data from an OpenMetrics file. #8084
[ENHANCEMENT] HTTP API: Fast-fail queries with only empty matchers. #8288
[ENHANCEMENT] HTTP API: Support matchers for labels API. #8301
[ENHANCEMENT] promtool: Improve checking of URLs passed on the command line. #7956
[ENHANCEMENT] SD: Expose IPv6 as a label in EC2 SD. #7086
[ENHANCEMENT] SD: Reuse EC2 client, reducing frequency of requesting credentials. #8311
[ENHANCEMENT] TSDB: Add logging when compaction takes more than the block time range. #8151
[ENHANCEMENT] TSDB: Avoid unnecessary GC runs after compaction. #8276
[BUGFIX] HTTP API: Avoid double-closing of channel when quitting multiple times via HTTP. #8242
[BUGFIX] SD: Ignore CNAME records in DNS SD to avoid spurious Invalid SRV record warnings. #8216
[BUGFIX] SD: Avoid config error triggered by valid label selectors in Kubernetes SD. #8285

### CODE REVIEW

**Comment by karlism** [comment]
@lest, can you please switch to [GitHub image registry](https://github.blog/2020-09-01-introducing-github-container-registry/) for centos-rpm-builder images? It looks like we're hitting new [docker hub limits](https://www.docker.com/increase-rate-limits). While you're at it, it probably be nice to update images to CentOS 7.9 and 8.3.

**Comment by lest** [comment]
@karlism yes, I like this idea.

I pushed images here:

https://github.com/lest/centos-rpm-builder-docker/packages/564926

They can be pulled as:

docker.pkg.github.com/lest/centos-rpm-builder-docker/centos-rpm-builder:8
docker.pkg.github.com/lest/centos-rpm-builder-docker/centos-rpm-builder:7

**Comment by karlism** [comment]
@lest, thanks. I've just tried to pull images locally and have issues with authentication:
```
# docker pull docker.pkg.github.com/lest/centos-rpm-builder-docker/centos-rpm-builder:8
Error response from daemon: Get https://docker.pkg.github.com/v2/lest/centos-rpm-builder-docker/centos-rpm-builder/manifests/8: no basic auth credentials
```
Same stuff if I try to build `node_exporter` package:
```
# make node_exporter
python3 ./generate.py --templates node_exporter
INFO:root:Building exporter node_exporter
tarball
sources
{'version': '1.0.1', 'package': '%{name}-%{version}.linux-amd64', 'tarball': 'https://github.com/prometheus/node_exporter/releases/download/v%{version}/%{name}-%{version}.linux-amd64.tar.gz', 'name': 'node_exporter', 'tarball_has_subdirectory': True, 'description': 'Prometheus exporter for hardware and OS metrics exposed by *NIX kernels,\nwritten in Go with pluggable metric collectors.\n', 'URL': 'https://github.com/prometheus/node_exporter', 'license': 'ASL 2.0', 'summary': 'Prometheus exporter for machine metrics, written in Go with pluggable metric collectors.', 'group': 'prometheus', 'sources': ['https://github.com/prometheus/node_exporter/releases/download/v%{version}/%{name}-%{version}.linux-amd64.tar.gz', 'autogen_%{name}.unit', '%{name}.default', 'autogen_%{name}.init'], 'user': 'prometheus', 'release': 1}
INFO:root:Rendering step init for node_exporter
INFO:root:Writing node_exporter step init to node_exporter/autogen_node_exporter.init
INFO:root:Rendering step spec for node_exporter
INFO:root:Writing node_exporter step spec to node_exporter/autogen_node_exporter.spec
INFO:root:Rendering step unit for node_exporter
INFO:root:Writing node_exporter step unit to node_exporter/autogen_node_exporter.unit
docker run -it --rm \
	-v /home/username/prometheus-rpm/node_exporter:/rpmbuild/SOURCES \
	-v /home/username/prometheus-rpm/_dist8:/rpmbuild/RPMS/x86_64 \
	-v /home/username/prometheus-rpm/_dist8:/rpmbuild/RPMS/noarch \
	docker.pkg.github.com/lest/centos-rpm-builder-docker/centos-rpm-builder:8 \
	build-spec SOURCES/autogen_node_exporter.spec
Unable to find image 'docker.pkg.github.com/lest/centos-rpm-builder-docker/centos-rpm-builder:8' locally
docker: Error response from daemon: Get https://docker.pkg.github.com/v2/lest/centos-rpm-builder-docker/centos-rpm-builder/manifests/8: no basic auth credentials.
See 'docker run --help'.
Makefile:83: recipe for target 'build8-node_exporter' failed
make: *** [build8-node_exporter] Error 125
```

Are you sure you made these images public?

**Comment by lest** [comment]
@karlism this is weird, the images should be public. I wonder if GitHub requires authentication even for public images. I'll check how to give public pull access and do some testing.

**Comment by lest** [comment]
@karlism looks like there is new GitHub Container Registry that works better.

Can you please try using the following?

```
docker pull ghcr.io/lest/centos-rpm-builder:8
docker pull ghcr.io/lest/centos-rpm-builder:7
```

**Comment by karlism** [comment]
@lest, thanks, looking good now, will update `Makefile` to use new images.

**Pull request merged**
