### PR TITLE
Updated to latest prometheus version

### PR DESCRIPTION
**Pull request by xocasdashdash**
Prometheus 2.15.1 is out.

### CODE REVIEW

**Comment by lest** [comment]
Thank you!

**Comment by xocasdashdash** [comment]
@lest have you thought of automating this kind of change? It should not be very hard for repositories like prometheus, alertmanager and so. Maybe it would be possible to do something like this with github actions that open up a PR when a new prometheus release is out?

**Comment by britcey** [comment]
I have a vague, hand-wavey TODO to write something to at least compare current versions vs. the 'current release' via the github api (for those projects that are using that).  I figure that'd be a step towards further automation.

Can you perform github actions on repos you don't control?  A quick search makes me think no, but perhaps I missed it.

**Comment by xocasdashdash** [comment]
@britcey No, you can't. But you can schedule them, which would be polling the available releases and changing the version if a new one is available. I think a little bit of python will be enough to parse the spec files, and then doing a search&replace on the spec file if a new is available.

**Comment by britcey** [comment]
@xocasdashdash that's roughly what I had in mind

**Pull request merged**
