### PR TITLE
Feature add couchbase exporter

### PR DESCRIPTION
**Pull request by pandrieux**
add https://github.com/blakelead/couchbase_exporter
version : Version: 0.9.5

couchbase database

### CODE REVIEW

**Comment by britcey** [comment]
- Why the switch of the docker image?

- why install to /opt instead of standard directories?

**Comment by pandrieux** [comment]
Sorry for late reply, I didn't see any notification of your comments.

- The builder image was not working. I have an error about owner/group using the default one.

- I choose /opt because couchbase_exporter needs to have (it is hard-coded) its json conf files in a directory named 'metrics', at same level of the binary

It can be somewhere else, but shouldn't be in '/bin' because of the config files. /opt sounds good to me according to Linux FHS.

**Comment by britcey** [comment]
(I though you should get notifications for activities on PRs you opened by default, but if not: cc: @pandrieux )

- The 'metrics' thing is an unfortunate design decision - using /opt makes sense to me in that case.

  On a related note, when trying to run it I get:

        could not use provided configuration file (/etc/couchbase_exporter.yml). Error: stat /opt/couchbase_exporter//etc/couchbase_exporter.yml: no such file or directory"

  because it looks like it is hardcoded to look for the specified config in the same directory as the binary (again, a not a great design decision, IMO).  So you'll need to either update .default file to reference /opt/couchbase_exporter/couchbase_exporter.yml or just skip specifying a config file.

  If you do specify a config, I would include a sample couchbase_exporter.yml, with the various options stubbed out (e.g., see thanos/thanos_alerts.yml)

- What error were you having with the docker image?  Your branch build OK for me with the existing image.  Changing the image would change it for _every_ package, so not something that should be done lightly.

**Comment by britcey** [comment]
I totally missed that the Makefile uses quay.io/zoonage/centos7-rpm-build for some sections & lest/centos7-rpm-builder for others; poking around, it looks like the zoonage Dockerfile is a fork of the lest Dockerfile, just adding 'yum-utils'.

I think it should be fine to standardize on the zoonage one.

@lest, any reason for the zoonage vs. lest images for the Centos 7 builds, or just some old logic?

**Comment by pandrieux** [comment]
That why I used zoonage Docker img, it is used in some other sections.

I will push a default config file, I missed it in the packaging.

**Comment by pandrieux** [comment]
Sorry for multiple commits... I did some long tests and the provided service script is not good since it is not informing its status changes. I'm removing the type and wathcdog in a new commit.
I also notify the maintainer on this matter.

**Comment by britcey** [comment]
Do you need changes from the maintainer or is this still suitable for packaging without upstream changes?

**Comment by pandrieux** [comment]
The maintainer is reactive he already accept my PR on this. I'm also updating a few missing metrics so we can have the first package fully up-to-date. I think it is better to package on the next release, I'm going to do it early January.

**Comment by pandrieux** [comment]
For the couchbase_exporter in version 0.9.6 it is OK on my side.

**Comment by pandrieux** [comment]
@britcey, is that OK to accept my PR so I can get the RPM from the repo ?

**Comment by britcey** [comment]
@lest can you comment on / merge https://github.com/lest/centos7-rpm-builder-docker/pull/2 so we can standardize on the lest/* docker images?  

@pandrieux let me see if we can clean that aspect up first.  Also not quite sure why this is showing all the other commits as part of the PR (but that's probably my lack of GH experience).

**Comment by lest** [comment]
I've updated the `lest/centos7-rpm-builder` image with the permissions fix and `yum-utils` added. I'll try to provide a CentOS 6 image soon.

Can you please isolate the changes with adding a new exporter so we can have them merged?

**Comment by pandrieux** [comment]
I've tested using the new `lest/centos7-rpm-builder` in target `$(PACKAGES7)` and it's working great now.
Do you want me to change back in the makefile ?

**Comment by lest** [comment]
Thank you!

**Pull request merged**
