### PR TITLE
Update Alertmanager to 0.22.0

### PR DESCRIPTION
**Pull request by karlism**
1) move alertmanager to templating
2) update to version 0.22.0
3) **move service parameters from systemd file to defaults**, this is breaking change which should finally resolve https://github.com/lest/prometheus-rpm/pull/97

@lest & @britcey, what are your thoughts on this?

### CODE REVIEW

**Comment by britcey** [comment]
I agree that we should (finally) move those options out of the service file - I don't think we have a good mechanism to warn people who will blindly install the updated RPM, so we should just rip the bandaid off.

One thing we'd lose from the custom .service file:

LimitNOFILE=65536

It's probably something we want to keep;  should we apply that across the board to the template or come up with an optional way to include things in the service file?  If the latter, we'd need to differentiate between the Unit, Service and/or Install sections.

The template also uses 'Restart=on-failure' instead of the current 'Restart=always' - but I _think_ that's OK.

**Comment by karlism** [comment]
> One thing we'd lose from the custom .service file:
> LimitNOFILE=65536

Just adjusted templates to support setting open file limits and set limit to 16384. Although I doubt it is really necessary as in my environment none of alertmanagers have more than ~30 open files, and I have cluster of 4 Alertmanagers and around 20 Prometheus servers as well as Thanos servers sending alerts there:
image

> The template also uses 'Restart=on-failure' instead of the current 'Restart=always' - but I _think_ that's OK.

Yeah, I guess that doesn't matter that much.

**Comment by britcey** [comment]
16k looks like more than enough - one of my Alertmanagers got over 1000 within the last 90 days, but otherwise looks similar to yours.

**Comment by TheMeier** [comment]
Could this directly be updated to 0.22.2?

**Comment by karlism** [comment]
@TheMeier, it will be updated to latest version automatically by [this script](https://github.com/lest/prometheus-rpm/blob/master/update_templating_versions.py).

**Comment by karlism** [comment]
Resolves https://github.com/lest/prometheus-rpm/issues/433

**Pull request merged**
