### PR TITLE
Add Mongodb exporter RPM

### PR DESCRIPTION
**Pull request by zoonage**
Adds the mongodb_exporter

### CODE REVIEW

**Comment by karlism** [comment]
@zoonage, gan you please fix license to `ASL 2.0`?

**Comment by zoonage** [comment]
> @zoonage, gan you please fix license to `ASL 2.0`?

Hi @karlism  can you clarify what you mean by this?

**Comment by karlism** [comment]
@zoonage, thanks, I guess you also need to create defaults file like [this one](https://github.com/lest/prometheus-rpm/blob/master/domain_exporter/domain_exporter.default) to fix the build.

**Comment by zoonage** [comment]
> @zoonage, thanks, I guess you also need to create defaults file like [this one](https://github.com/lest/prometheus-rpm/blob/master/domain_exporter/domain_exporter.default) to fix the build.

Forgot to git add the file, pushed that up now, I've got the build RPM for centos 7 running in a testing environment atm as well

**Comment by karlism** [comment]
Thanks!

**Pull request merged**
