### PR TITLE
Added prometheus2 version 2.0.0

### PR DESCRIPTION
**Pull request by edgarswed**
Added prometheus 2.0 as separate package.

### CODE REVIEW

**Comment by lest** [comment]
Thank you! Can you please update `Makefile` to build the new package?

**Comment by edgarswed** [comment]
Sure, just did it.

**Comment by lest** [comment]
The spec file needs to be named `prometheus2.spec` to make the build work without a need for extra changes. Other files in the `prometheus2` directory should stay as they currently are.

Could you please rename `prometheus2/prometheus.spec` to `prometheus2/prometheus2.spec`?

**Comment by lest** [comment]
Thank you! The package will be available in the repository shortly.

**Comment by edgarswed** [comment]
> Could you please rename prometheus2/prometheus.spec to prometheus2/prometheus2.spec?

Yeap, and .service file also renamed because of different flag/syntax comparing to prometheus1

**Comment by edgarswed** [comment]
Thank you.

**Comment by lest** [comment]
> Yeap, and .service file also renamed because of different flag/syntax comparing to prometheus1

I don't think there is need to rename the systemd service as we have `Conflicts: prometheus` in the spec so two versions cannot be installed at the same time.

Actually, the service will still stay as `prometheus.service` after installation because of the following line:

```
install -m 644 %{SOURCE1} %{buildroot}/usr/lib/systemd/system/prometheus.service
```

I think all is well. I'm planning on migrating my Prometheus installation to version 2 this month, so your pull request is very helpful. Thank you!

**Pull request merged**
