### PR TITLE
Update Redis and HAProxy exporters

### PR DESCRIPTION
**Pull request by zoonage**
#52 

Some improvements to template generation to simplify the script & use features of YAML.

Update Redis and HAproxy exporters and move to the templating method

### CODE REVIEW

**Comment by zoonage** [comment]
Will look into this when I have time

**Comment by zoonage** [comment]
@lest Finally got Travis working, can you review please?

**Comment by zoonage** [comment]
@lest any chance you'll have a chance to look at this?

**Comment by lest** [comment]
Looks good

**Pull request merged**
