### PR TITLE
Update Prometheus to 2.26.0 and rename package

### PR DESCRIPTION
**Pull request by karlism**
1. update Prometheus to 2.26.0
2. rename package from `prometheus2` to `prometheus`, `Obsolete` parameter in package should provide smooth update, but I haven't had chance to test it with remote repository, only by installing package from file system
3. move web console parameters from service file to defaults, this is breaking change

### CODE REVIEW

**Comment by lest** [comment]
@karlism will the package name change require users with prometheus2 installed to do something manually to use the latest prometheus package?

**Comment by karlism** [comment]
@lest, package should upgrade successfully, but these parameters will be moved to /etc/defaults/prometheus:
https://github.com/lest/prometheus-rpm/pull/390/commits/99cb3ff7a052c4c2c49d19d67e74582f5c8afa80
Users with modified defaults file might experience issues

**Comment by lest** [comment]
@karlism I think we can clear files for building prometheus 1.x packages since it's very unlikely for it to receive another update. I'm not sure about renaming the prometheus2 package though, it might be better to keep it as prometheus2 so we can have it side by side with prometheus3 that will appear at some point in future.

Let's hear @britcey thoughts.

**Comment by britcey** [comment]
Bearing in mind I'm no RPM expert:

I agree the 1.x series isn't coming back;  how did Red Hat handle Python going from 1.x to 2.x?  The basic 'python' package is Python 2.x;  'yum install python' and 'yum install python2' will install the same packages.  Will the python3 packages just become 'python' when Python 2.x is officially retired?

I think I'd be fine with prometheus2 becoming 'prometheus', but can we still have 'yum install prometheus2' install that package?  How does that work, a meta-packages with just a dependency listed?

re: breaking changes - I wish we had a better way of indicating such things to the users but I don't want to be hostage to old, incorrect decisions.  I'm OK with changing the defaults.  Do we want to update the main-page README with something at the time for these sorts of breaking package changes?

**Comment by karlism** [comment]
> @karlism I think we can clear files for building prometheus 1.x packages since it's very unlikely for it to receive another update.

Prometheus 1.x has been removed from repository almost year ago: https://github.com/lest/prometheus-rpm/pull/220

> I'm not sure about renaming the prometheus2 package though, it might be better to keep it as prometheus2 so we can have it side by side with prometheus3 that will appear at some point in future.

I don't think that is is something to be concerned about, when Prometheus 1.x was around package was also called `prometheus`, not `prometheus1`. When Prometheus 3.x is released we can have `prometheus` and `prometheus3` packages. Proposed package name change is in line with what we have for other packages, e.g., we do not have `ssl_exporter2` package for SSL exporter 2.2.0.

> I think I'd be fine with prometheus2 becoming 'prometheus', but can we still have 'yum install prometheus2' install that package?

Yes, I will have to add `Provides: prometheus2` to spec file in order to achieve that and I think this is good idea for compatibility.

**Comment by britcey** [comment]
That's a good point re: the consoles - my impression is that they're a little-used feature at this point.  I wouldn't be surprised to see them dropped altogether at some point.

As far as potentially breaking changes goes, I agree that people may not even notice this one.

**Comment by karlism** [comment]
@lest, any further comments on this?

**Comment by perkons** [comment]
any updates on this?

**Comment by mator** [comment]
> Yes, I will have to add `Provides: prometheus2` to spec file in order to achieve that and I think this is good idea for compatibility.

maybe other way around? i.e. leave package name as prometheus2, but put to rpm.spec file `Provides: prometheus` ?

**Comment by karlism** [comment]
@mator, that's also an option. At this point I do not really care but would like to update Prometheus to never version as we're already multiple releases behind.

@lest, can you please look into this? There is a [security vulnerability](https://github.com/prometheus/prometheus/security/advisories/GHSA-vx57-7f4q-fpc7) in all 2.23+ versions of Prometheus that has been addressed in 2.26.1 and 2.27.1 versions.

**Comment by lest** [comment]
@karlism I like the idea or keeping prometheus2 package name and having it `Provides: prometheus`. It reminds me of how I think python packages are usually organized.

**Pull request merged**
